name: phishing_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.2.1
  - numpy=1.24.3
  - pandas=2.0.3
  - pytorch=2.1.0
  - cudatoolkit=11.8
  - spacy=3.7.2
  - nltk=3.8.1
  - scikit-learn=1.3.0
  - pip:
    - transformers==4.34.0
    - fastapi==0.104.0
    - uvicorn==0.23.2
    - pydantic==2.4.2
    - sqlalchemy==2.0.21
    - psycopg2-binary==2.9.9
    - pika==1.3.1
    - redis==5.0.1
    - python-dotenv==1.0.0
    - spacy-transformers==1.3.4
    - beautifulsoup4==4.12.2 